name: Build images

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write  # Required for pushing images to GitHub Container Registry

jobs:
  build-docker-images:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04

    steps:
      - name: Free disk space
        uses: khulnasoft-lab/free-disk-space@master

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push hub image
        run: |
          docker build -f cmd/artifacthub/Dockerfile -t ghcr.io/${{ github.repository_owner }}/hub:$GITHUB_SHA .
          docker push ghcr.io/${{ github.repository_owner }}/hub:$GITHUB_SHA

      - name: Build, tag, and push db-migrator image
        run: |
          docker build -f database/migrations/Dockerfile -t ghcr.io/${{ github.repository_owner }}/db-migrator:$GITHUB_SHA .
          docker push ghcr.io/${{ github.repository_owner }}/db-migrator:$GITHUB_SHA

      - name: Build, tag, and push scanner image
        run: |
          docker build -f cmd/scanner/Dockerfile -t ghcr.io/${{ github.repository_owner }}/scanner:$GITHUB_SHA .
          docker push ghcr.io/${{ github.repository_owner }}/scanner:$GITHUB_SHA

      - name: Build, tag, and push tracker image
        run: |
          docker build -f cmd/tracker/Dockerfile -t ghcr.io/${{ github.repository_owner }}/tracker:$GITHUB_SHA .
          docker push ghcr.io/${{ github.repository_owner }}/tracker:$GITHUB_SHA
